//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AksemovExamEntities : DbContext
    {
        public AksemovExamEntities()
            : base("name=AksemovExamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Сведения_О_Вопросах_Теста> Сведения_О_Вопросах_Теста { get; set; }
        public virtual DbSet<Сведения_О_Студентах> Сведения_О_Студентах { get; set; }
        public virtual DbSet<Сведения_О_тестировании> Сведения_О_тестировании { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
    }
}
