//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сведения_О_Вопросах_Теста
    {
        public int ID { get; set; }
        public string Вид_вопроса { get; set; }
        public string вопрос { get; set; }
        public string Вариант_ответа_1 { get; set; }
        public string Вариант_ответа_2 { get; set; }
        public string Вариант_ответа_3 { get; set; }
        public string Вариант_ответа_4 { get; set; }
        public string Правильный_ответ { get; set; }
    }
}
