//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сведения_О_тестировании
    {
        public string ID_Тестирования { get; set; }
        public string Дата { get; set; }
        public Nullable<int> ID_Студента { get; set; }
        public Nullable<int> Время_На_Тест { get; set; }
        public Nullable<int> Количество_вопросов_в_тесте { get; set; }
        public Nullable<int> Количество_правильных_ответов { get; set; }
        public Nullable<int> Оценка { get; set; }
    
        public virtual Сведения_О_Студентах Сведения_О_Студентах { get; set; }
    }
}
