//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сведения_О_Студентах
    {
        public Сведения_О_Студентах()
        {
            this.Сведения_О_тестировании = new HashSet<Сведения_О_тестировании>();
        }
    
        public int ID_студента { get; set; }
        public Nullable<int> Номер_зачетной_книжки { get; set; }
        public string Учебная_группа { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
    
        public virtual ICollection<Сведения_О_тестировании> Сведения_О_тестировании { get; set; }
    }
}
